Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -4,10 +4,12 @@
 name: Python application
 
 on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+  schedule:
+    - cron: "2 * * * *"
+#   push:
+#     branches: [ main ]
+#   pull_request:
+#     branches: [ main ]
 
 jobs:
   build:
@@ -25,21 +27,21 @@ jobs:
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-    - name: checking external package
-      run: |
-        if ! which requests > /dev/null; then
-          echo "not found"
-          pip install requests
-        fi
-    - name: checking external python
-      run: |
-        if which python > /dev/null; then
-          echo "python found"
-        fi  
-        if ! which python > /dev/null; then
-          echo "not found"
-          pip install python
-        fi   
+#     - name: checking external package
+#       run: |
+#         if ! which requests > /dev/null; then
+#           echo "not found"
+#           pip install requests
+#         fi
+#     - name: checking external python
+#       run: |
+#         if which python > /dev/null; then
+#           echo "python found"
+#         fi  
+#         if ! which python > /dev/null; then
+#           echo "not found"
+#           pip install python
+#         fi   
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
